"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""


from setuptools import setup

APP = ['RPiPemeter.py']
APP_NAME = "PowerMeter"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'iconfile': '/Users/greg/GoogleDrive/Work/ExperimentalSetup/PythonSoftware/InstrumentControl/RpiPoweMeter/UI/Icons.ico',
        'CFBundleGetInfoString': "Power Meter for Insertion Losses",
        'CFBundleIdentifier': "com.gmoille.osx.powermetter",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2019, Gregory Moille, All Rights Reserved",
        'PyRuntimeLocations': [
                '@executable_path/../Frameworks/libpython3.7m.dylib',
                '/Users/greg/anaconda3/lib/libpython3.7m.dylib'
               ]
    }
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
